#!/usr/bin/env python3

import subprocess
from sys import argv

if len(argv) < 5 or argv[1] == "--help" or argv[1] == "-h":
	print("Usage: (input filename) (output filename) (first silence start in seconds) (first silence end in seconds) ... (last silence start in seconds) (last silence end in seconds)")
	exit()
af_string = ''
for i in range(3, len(argv), 2):
	af_string += f"volume=enable='between(t,{argv[i]},{argv[i + 1]})':volume=0, "
af_string = af_string[0:-2]
arg_list = ["ffmpeg", "-i", argv[1], "-c:v", "copy", "-af", af_string, argv[2]]
print("Executing: " + ' '.join(arg_list))
subprocess.run(arg_list)
