#!/usr/bin/env python3
#Inserts spaces between all characters in argvand outputs the result.

def spaceout(s):
	add = 0
	for i in range(1, len(s)):
		ii = i + add
		if not s[ii - 1].isspace() and not s[ii].isspace():
			s = s[:ii] + ' ' + s[ii:]
			add += 1
	return s
	
def main():
	import sys
	for i in range(1, len(sys.argv)):
		print(spaceout(sys.argv[i]))

if __name__ == "__main__":
	main()
